apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: remedy-controller-azure
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - azure.remedy.gardener.cloud
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - "*"
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - "*"
